namespace WildCat_Tickets
{
    partial class ViewProfileForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ViewProfileForm));
            SiticoneNetFrameworkUI.SiticoneFlowPanel.LayoutState layoutState1 = new SiticoneNetFrameworkUI.SiticoneFlowPanel.LayoutState();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.birthDateTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.yearTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.fnameLabel = new System.Windows.Forms.Label();
            this.programTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.mnameLabel = new System.Windows.Forms.Label();
            this.phoneTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.lnameLabel = new System.Windows.Forms.Label();
            this.emailTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.programLabel = new System.Windows.Forms.Label();
            this.lNameTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.yearLabel = new System.Windows.Forms.Label();
            this.mNameTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.bdateLabel = new System.Windows.Forms.Label();
            this.fNameTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.emailLabel = new System.Windows.Forms.Label();
            this.uploadProfilePhotoBtn = new SiticoneNetFrameworkUI.SiticoneButton();
            this.phoneLabel = new System.Windows.Forms.Label();
            this.profilePictureBox = new FontAwesome.Sharp.IconPictureBox();
            this.profileContainer = new System.Windows.Forms.Panel();
            this.deleteBtn = new SiticoneNetFrameworkUI.SiticoneButton();
            this.label1 = new System.Windows.Forms.Label();
            this.idNumberTbx = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.saveBtn = new SiticoneNetFrameworkUI.SiticoneButton();
            this.cancelBtn = new SiticoneNetFrameworkUI.SiticoneButton();
            this.editBtn = new SiticoneNetFrameworkUI.SiticoneButton();
            this.mySiticoneLicenseSettings1 = new SiticoneNetFrameworkUI.MySiticoneLicenseSettings();
            ((System.ComponentModel.ISupportInitialize)(this.profilePictureBox)).BeginInit();
            this.profileContainer.SuspendLayout();
            this.SuspendLayout();
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // birthDateTbx
            // 
            this.birthDateTbx.AccessibleDescription = "A customizable text input field.";
            this.birthDateTbx.AccessibleName = "Text Box";
            this.birthDateTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.birthDateTbx.BackColor = System.Drawing.Color.Transparent;
            this.birthDateTbx.BlinkCount = 3;
            this.birthDateTbx.BlinkShadow = false;
            this.birthDateTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.birthDateTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.birthDateTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.birthDateTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.birthDateTbx.CanShake = true;
            this.birthDateTbx.ContinuousBlink = false;
            this.birthDateTbx.CornerRadiusBottomLeft = 10;
            this.birthDateTbx.CornerRadiusBottomRight = 10;
            this.birthDateTbx.CornerRadiusTopLeft = 10;
            this.birthDateTbx.CornerRadiusTopRight = 10;
            this.birthDateTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.birthDateTbx.CursorBlinkRate = 500;
            this.birthDateTbx.CursorColor = System.Drawing.Color.Black;
            this.birthDateTbx.CursorHeight = 0;
            this.birthDateTbx.CursorOffset = 0;
            this.birthDateTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.birthDateTbx.CursorWidth = 1;
            this.birthDateTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.birthDateTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.birthDateTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.birthDateTbx.EnableDropShadow = false;
            this.birthDateTbx.FillColor1 = System.Drawing.Color.White;
            this.birthDateTbx.FillColor2 = System.Drawing.Color.White;
            this.birthDateTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.birthDateTbx.ForeColor = System.Drawing.Color.DimGray;
            this.birthDateTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.birthDateTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.birthDateTbx.IsEnabled = true;
            this.birthDateTbx.IsReadOnly = true;
            this.birthDateTbx.Location = new System.Drawing.Point(367, 336);
            this.birthDateTbx.Name = "birthDateTbx";
            this.birthDateTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.birthDateTbx.PlaceholderText = "BirthDate";
            this.birthDateTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.birthDateTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.birthDateTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.birthDateTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.birthDateTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.birthDateTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.birthDateTbx.ShadowAnimationDuration = 1;
            this.birthDateTbx.ShadowBlur = 10;
            this.birthDateTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.birthDateTbx.Size = new System.Drawing.Size(150, 40);
            this.birthDateTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.birthDateTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.birthDateTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.birthDateTbx.SolidFillColor = System.Drawing.Color.White;
            this.birthDateTbx.TabIndex = 9;
            this.birthDateTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.birthDateTbx.ValidationErrorMessage = "Invalid input.";
            this.birthDateTbx.ValidationFunction = null;
            // 
            // yearTbx
            // 
            this.yearTbx.AccessibleDescription = "A customizable text input field.";
            this.yearTbx.AccessibleName = "Text Box";
            this.yearTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.yearTbx.BackColor = System.Drawing.Color.Transparent;
            this.yearTbx.BlinkCount = 3;
            this.yearTbx.BlinkShadow = false;
            this.yearTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.yearTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.yearTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.yearTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.yearTbx.CanShake = true;
            this.yearTbx.ContinuousBlink = false;
            this.yearTbx.CornerRadiusBottomLeft = 10;
            this.yearTbx.CornerRadiusBottomRight = 10;
            this.yearTbx.CornerRadiusTopLeft = 10;
            this.yearTbx.CornerRadiusTopRight = 10;
            this.yearTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.yearTbx.CursorBlinkRate = 500;
            this.yearTbx.CursorColor = System.Drawing.Color.Black;
            this.yearTbx.CursorHeight = 0;
            this.yearTbx.CursorOffset = 0;
            this.yearTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.yearTbx.CursorWidth = 1;
            this.yearTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.yearTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.yearTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.yearTbx.EnableDropShadow = false;
            this.yearTbx.FillColor1 = System.Drawing.Color.White;
            this.yearTbx.FillColor2 = System.Drawing.Color.White;
            this.yearTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.yearTbx.ForeColor = System.Drawing.Color.DimGray;
            this.yearTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.yearTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.yearTbx.IsEnabled = true;
            this.yearTbx.IsReadOnly = true;
            this.yearTbx.Location = new System.Drawing.Point(367, 277);
            this.yearTbx.Name = "yearTbx";
            this.yearTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.yearTbx.PlaceholderText = "Year";
            this.yearTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.yearTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.yearTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.yearTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.yearTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.yearTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.yearTbx.ShadowAnimationDuration = 1;
            this.yearTbx.ShadowBlur = 10;
            this.yearTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.yearTbx.Size = new System.Drawing.Size(150, 40);
            this.yearTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.yearTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.yearTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.yearTbx.SolidFillColor = System.Drawing.Color.White;
            this.yearTbx.TabIndex = 6;
            this.yearTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.yearTbx.ValidationErrorMessage = "Invalid input.";
            this.yearTbx.ValidationFunction = null;
            // 
            // fnameLabel
            // 
            this.fnameLabel.AutoSize = true;
            this.fnameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.fnameLabel.Location = new System.Drawing.Point(52, 202);
            this.fnameLabel.Name = "fnameLabel";
            this.fnameLabel.Size = new System.Drawing.Size(44, 9);
            this.fnameLabel.TabIndex = 10;
            this.fnameLabel.Text = "First Name";
            // 
            // programTbx
            // 
            this.programTbx.AccessibleDescription = "A customizable text input field.";
            this.programTbx.AccessibleName = "Text Box";
            this.programTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.programTbx.BackColor = System.Drawing.Color.Transparent;
            this.programTbx.BlinkCount = 3;
            this.programTbx.BlinkShadow = false;
            this.programTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.programTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.programTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.programTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.programTbx.CanShake = true;
            this.programTbx.ContinuousBlink = false;
            this.programTbx.CornerRadiusBottomLeft = 10;
            this.programTbx.CornerRadiusBottomRight = 10;
            this.programTbx.CornerRadiusTopLeft = 10;
            this.programTbx.CornerRadiusTopRight = 10;
            this.programTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.programTbx.CursorBlinkRate = 500;
            this.programTbx.CursorColor = System.Drawing.Color.Black;
            this.programTbx.CursorHeight = 0;
            this.programTbx.CursorOffset = 0;
            this.programTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.programTbx.CursorWidth = 1;
            this.programTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.programTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.programTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.programTbx.EnableDropShadow = false;
            this.programTbx.FillColor1 = System.Drawing.Color.White;
            this.programTbx.FillColor2 = System.Drawing.Color.White;
            this.programTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.programTbx.ForeColor = System.Drawing.Color.DimGray;
            this.programTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.programTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.programTbx.IsEnabled = true;
            this.programTbx.IsReadOnly = true;
            this.programTbx.Location = new System.Drawing.Point(55, 277);
            this.programTbx.Name = "programTbx";
            this.programTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.programTbx.PlaceholderText = "Program";
            this.programTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.programTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.programTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.programTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.programTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.programTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.programTbx.ShadowAnimationDuration = 1;
            this.programTbx.ShadowBlur = 10;
            this.programTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.programTbx.Size = new System.Drawing.Size(306, 40);
            this.programTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.programTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.programTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.programTbx.SolidFillColor = System.Drawing.Color.White;
            this.programTbx.TabIndex = 5;
            this.programTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.programTbx.ValidationErrorMessage = "Invalid input.";
            this.programTbx.ValidationFunction = null;
            // 
            // mnameLabel
            // 
            this.mnameLabel.AutoSize = true;
            this.mnameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.mnameLabel.Location = new System.Drawing.Point(208, 202);
            this.mnameLabel.Name = "mnameLabel";
            this.mnameLabel.Size = new System.Drawing.Size(28, 9);
            this.mnameLabel.TabIndex = 11;
            this.mnameLabel.Text = "Middle";
            // 
            // phoneTbx
            // 
            this.phoneTbx.AccessibleDescription = "A customizable text input field.";
            this.phoneTbx.AccessibleName = "Text Box";
            this.phoneTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.phoneTbx.BackColor = System.Drawing.Color.Transparent;
            this.phoneTbx.BlinkCount = 3;
            this.phoneTbx.BlinkShadow = false;
            this.phoneTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.phoneTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.phoneTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.phoneTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.phoneTbx.CanShake = true;
            this.phoneTbx.ContinuousBlink = false;
            this.phoneTbx.CornerRadiusBottomLeft = 10;
            this.phoneTbx.CornerRadiusBottomRight = 10;
            this.phoneTbx.CornerRadiusTopLeft = 10;
            this.phoneTbx.CornerRadiusTopRight = 10;
            this.phoneTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneTbx.CursorBlinkRate = 500;
            this.phoneTbx.CursorColor = System.Drawing.Color.Black;
            this.phoneTbx.CursorHeight = 0;
            this.phoneTbx.CursorOffset = 0;
            this.phoneTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.phoneTbx.CursorWidth = 1;
            this.phoneTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.phoneTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.phoneTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.phoneTbx.EnableDropShadow = false;
            this.phoneTbx.FillColor1 = System.Drawing.Color.White;
            this.phoneTbx.FillColor2 = System.Drawing.Color.White;
            this.phoneTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.phoneTbx.ForeColor = System.Drawing.Color.DimGray;
            this.phoneTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.phoneTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.phoneTbx.IsEnabled = true;
            this.phoneTbx.IsReadOnly = true;
            this.phoneTbx.Location = new System.Drawing.Point(367, 395);
            this.phoneTbx.Name = "phoneTbx";
            this.phoneTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.phoneTbx.PlaceholderText = "Phone1";
            this.phoneTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.phoneTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.phoneTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.phoneTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.phoneTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.phoneTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.phoneTbx.ShadowAnimationDuration = 1;
            this.phoneTbx.ShadowBlur = 10;
            this.phoneTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.phoneTbx.Size = new System.Drawing.Size(150, 40);
            this.phoneTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.phoneTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.phoneTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.phoneTbx.SolidFillColor = System.Drawing.Color.White;
            this.phoneTbx.TabIndex = 8;
            this.phoneTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.phoneTbx.ValidationErrorMessage = "Invalid input.";
            this.phoneTbx.ValidationFunction = null;
            // 
            // lnameLabel
            // 
            this.lnameLabel.AutoSize = true;
            this.lnameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lnameLabel.Location = new System.Drawing.Point(364, 202);
            this.lnameLabel.Name = "lnameLabel";
            this.lnameLabel.Size = new System.Drawing.Size(42, 9);
            this.lnameLabel.TabIndex = 12;
            this.lnameLabel.Text = "Last Name";
            // 
            // emailTbx
            // 
            this.emailTbx.AccessibleDescription = "A customizable text input field.";
            this.emailTbx.AccessibleName = "Text Box";
            this.emailTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.emailTbx.BackColor = System.Drawing.Color.Transparent;
            this.emailTbx.BlinkCount = 3;
            this.emailTbx.BlinkShadow = false;
            this.emailTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.emailTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.emailTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.emailTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.emailTbx.CanShake = true;
            this.emailTbx.ContinuousBlink = false;
            this.emailTbx.CornerRadiusBottomLeft = 10;
            this.emailTbx.CornerRadiusBottomRight = 10;
            this.emailTbx.CornerRadiusTopLeft = 10;
            this.emailTbx.CornerRadiusTopRight = 10;
            this.emailTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailTbx.CursorBlinkRate = 500;
            this.emailTbx.CursorColor = System.Drawing.Color.Black;
            this.emailTbx.CursorHeight = 0;
            this.emailTbx.CursorOffset = 0;
            this.emailTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.emailTbx.CursorWidth = 1;
            this.emailTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.emailTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.emailTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.emailTbx.EnableDropShadow = false;
            this.emailTbx.FillColor1 = System.Drawing.Color.White;
            this.emailTbx.FillColor2 = System.Drawing.Color.White;
            this.emailTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.emailTbx.ForeColor = System.Drawing.Color.DimGray;
            this.emailTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.emailTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.emailTbx.IsEnabled = true;
            this.emailTbx.IsReadOnly = true;
            this.emailTbx.Location = new System.Drawing.Point(55, 395);
            this.emailTbx.Name = "emailTbx";
            this.emailTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.emailTbx.PlaceholderText = "Email";
            this.emailTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.emailTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.emailTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.emailTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.emailTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.emailTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.emailTbx.ShadowAnimationDuration = 1;
            this.emailTbx.ShadowBlur = 10;
            this.emailTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.emailTbx.Size = new System.Drawing.Size(306, 40);
            this.emailTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.emailTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.emailTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.emailTbx.SolidFillColor = System.Drawing.Color.White;
            this.emailTbx.TabIndex = 7;
            this.emailTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.emailTbx.ValidationErrorMessage = "Invalid input.";
            this.emailTbx.ValidationFunction = null;
            // 
            // programLabel
            // 
            this.programLabel.AutoSize = true;
            this.programLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.programLabel.Location = new System.Drawing.Point(52, 261);
            this.programLabel.Name = "programLabel";
            this.programLabel.Size = new System.Drawing.Size(35, 9);
            this.programLabel.TabIndex = 13;
            this.programLabel.Text = "Program";
            // 
            // lNameTbx
            // 
            this.lNameTbx.AccessibleDescription = "A customizable text input field.";
            this.lNameTbx.AccessibleName = "Text Box";
            this.lNameTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.lNameTbx.BackColor = System.Drawing.Color.Transparent;
            this.lNameTbx.BlinkCount = 3;
            this.lNameTbx.BlinkShadow = false;
            this.lNameTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.lNameTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.lNameTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.lNameTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.lNameTbx.CanShake = true;
            this.lNameTbx.ContinuousBlink = false;
            this.lNameTbx.CornerRadiusBottomLeft = 10;
            this.lNameTbx.CornerRadiusBottomRight = 10;
            this.lNameTbx.CornerRadiusTopLeft = 10;
            this.lNameTbx.CornerRadiusTopRight = 10;
            this.lNameTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lNameTbx.CursorBlinkRate = 500;
            this.lNameTbx.CursorColor = System.Drawing.Color.Black;
            this.lNameTbx.CursorHeight = 0;
            this.lNameTbx.CursorOffset = 0;
            this.lNameTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.lNameTbx.CursorWidth = 1;
            this.lNameTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.lNameTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.lNameTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.lNameTbx.EnableDropShadow = false;
            this.lNameTbx.FillColor1 = System.Drawing.Color.White;
            this.lNameTbx.FillColor2 = System.Drawing.Color.White;
            this.lNameTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lNameTbx.ForeColor = System.Drawing.Color.DimGray;
            this.lNameTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.lNameTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.lNameTbx.IsEnabled = true;
            this.lNameTbx.IsReadOnly = true;
            this.lNameTbx.Location = new System.Drawing.Point(367, 218);
            this.lNameTbx.Name = "lNameTbx";
            this.lNameTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.lNameTbx.PlaceholderText = "Last Name";
            this.lNameTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.lNameTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.lNameTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.lNameTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.lNameTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.lNameTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.lNameTbx.ShadowAnimationDuration = 1;
            this.lNameTbx.ShadowBlur = 10;
            this.lNameTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.lNameTbx.Size = new System.Drawing.Size(150, 40);
            this.lNameTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.lNameTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.lNameTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.lNameTbx.SolidFillColor = System.Drawing.Color.White;
            this.lNameTbx.TabIndex = 4;
            this.lNameTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.lNameTbx.ValidationErrorMessage = "Invalid input.";
            this.lNameTbx.ValidationFunction = null;
            // 
            // yearLabel
            // 
            this.yearLabel.AutoSize = true;
            this.yearLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.yearLabel.Location = new System.Drawing.Point(367, 261);
            this.yearLabel.Name = "yearLabel";
            this.yearLabel.Size = new System.Drawing.Size(21, 9);
            this.yearLabel.TabIndex = 14;
            this.yearLabel.Text = "Year";
            // 
            // mNameTbx
            // 
            this.mNameTbx.AccessibleDescription = "A customizable text input field.";
            this.mNameTbx.AccessibleName = "Text Box";
            this.mNameTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.mNameTbx.BackColor = System.Drawing.Color.Transparent;
            this.mNameTbx.BlinkCount = 3;
            this.mNameTbx.BlinkShadow = false;
            this.mNameTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.mNameTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.mNameTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.mNameTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.mNameTbx.CanShake = true;
            this.mNameTbx.ContinuousBlink = false;
            this.mNameTbx.CornerRadiusBottomLeft = 10;
            this.mNameTbx.CornerRadiusBottomRight = 10;
            this.mNameTbx.CornerRadiusTopLeft = 10;
            this.mNameTbx.CornerRadiusTopRight = 10;
            this.mNameTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.mNameTbx.CursorBlinkRate = 500;
            this.mNameTbx.CursorColor = System.Drawing.Color.Black;
            this.mNameTbx.CursorHeight = 0;
            this.mNameTbx.CursorOffset = 0;
            this.mNameTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.mNameTbx.CursorWidth = 1;
            this.mNameTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.mNameTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.mNameTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.mNameTbx.EnableDropShadow = false;
            this.mNameTbx.FillColor1 = System.Drawing.Color.White;
            this.mNameTbx.FillColor2 = System.Drawing.Color.White;
            this.mNameTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.mNameTbx.ForeColor = System.Drawing.Color.DimGray;
            this.mNameTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.mNameTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.mNameTbx.IsEnabled = true;
            this.mNameTbx.IsReadOnly = true;
            this.mNameTbx.Location = new System.Drawing.Point(211, 218);
            this.mNameTbx.Name = "mNameTbx";
            this.mNameTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.mNameTbx.PlaceholderText = "Middle";
            this.mNameTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.mNameTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.mNameTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.mNameTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.mNameTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.mNameTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.mNameTbx.ShadowAnimationDuration = 1;
            this.mNameTbx.ShadowBlur = 10;
            this.mNameTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.mNameTbx.Size = new System.Drawing.Size(150, 40);
            this.mNameTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.mNameTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.mNameTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.mNameTbx.SolidFillColor = System.Drawing.Color.White;
            this.mNameTbx.TabIndex = 3;
            this.mNameTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.mNameTbx.ValidationErrorMessage = "Invalid input.";
            this.mNameTbx.ValidationFunction = null;
            // 
            // bdateLabel
            // 
            this.bdateLabel.AutoSize = true;
            this.bdateLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bdateLabel.Location = new System.Drawing.Point(364, 320);
            this.bdateLabel.Name = "bdateLabel";
            this.bdateLabel.Size = new System.Drawing.Size(95, 9);
            this.bdateLabel.TabIndex = 15;
            this.bdateLabel.Text = "Birthdate (YYYY-MM-DD)";
            // 
            // fNameTbx
            // 
            this.fNameTbx.AccessibleDescription = "A customizable text input field.";
            this.fNameTbx.AccessibleName = "Text Box";
            this.fNameTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.fNameTbx.BackColor = System.Drawing.Color.Transparent;
            this.fNameTbx.BlinkCount = 3;
            this.fNameTbx.BlinkShadow = false;
            this.fNameTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.fNameTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.fNameTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.fNameTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.fNameTbx.CanShake = true;
            this.fNameTbx.ContinuousBlink = false;
            this.fNameTbx.CornerRadiusBottomLeft = 10;
            this.fNameTbx.CornerRadiusBottomRight = 10;
            this.fNameTbx.CornerRadiusTopLeft = 10;
            this.fNameTbx.CornerRadiusTopRight = 10;
            this.fNameTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.fNameTbx.CursorBlinkRate = 500;
            this.fNameTbx.CursorColor = System.Drawing.Color.Black;
            this.fNameTbx.CursorHeight = 0;
            this.fNameTbx.CursorOffset = 0;
            this.fNameTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.fNameTbx.CursorWidth = 1;
            this.fNameTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.fNameTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.fNameTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.fNameTbx.EnableDropShadow = false;
            this.fNameTbx.FillColor1 = System.Drawing.Color.White;
            this.fNameTbx.FillColor2 = System.Drawing.Color.White;
            this.fNameTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.fNameTbx.ForeColor = System.Drawing.Color.DimGray;
            this.fNameTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.fNameTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.fNameTbx.IsEnabled = true;
            this.fNameTbx.IsReadOnly = true;
            this.fNameTbx.Location = new System.Drawing.Point(55, 218);
            this.fNameTbx.Name = "fNameTbx";
            this.fNameTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.fNameTbx.PlaceholderText = "First Name";
            this.fNameTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.fNameTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.fNameTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.fNameTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.fNameTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.fNameTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.fNameTbx.ShadowAnimationDuration = 1;
            this.fNameTbx.ShadowBlur = 10;
            this.fNameTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.fNameTbx.Size = new System.Drawing.Size(150, 40);
            this.fNameTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.fNameTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.fNameTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.fNameTbx.SolidFillColor = System.Drawing.Color.White;
            this.fNameTbx.TabIndex = 2;
            this.fNameTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.fNameTbx.ValidationErrorMessage = "Invalid input.";
            this.fNameTbx.ValidationFunction = null;
            // 
            // emailLabel
            // 
            this.emailLabel.AutoSize = true;
            this.emailLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.emailLabel.Location = new System.Drawing.Point(52, 379);
            this.emailLabel.Name = "emailLabel";
            this.emailLabel.Size = new System.Drawing.Size(25, 9);
            this.emailLabel.TabIndex = 16;
            this.emailLabel.Text = "Email";
            // 
            // uploadProfilePhotoBtn
            // 
            this.uploadProfilePhotoBtn.AccessibleDescription = "";
            this.uploadProfilePhotoBtn.AccessibleName = "UPLOAD";
            this.uploadProfilePhotoBtn.AutoSizeBasedOnText = false;
            this.uploadProfilePhotoBtn.BackColor = System.Drawing.Color.Transparent;
            this.uploadProfilePhotoBtn.BadgeBackColor = System.Drawing.Color.Red;
            this.uploadProfilePhotoBtn.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.uploadProfilePhotoBtn.BadgeValue = 0;
            this.uploadProfilePhotoBtn.BadgeValueForeColor = System.Drawing.Color.Black;
            this.uploadProfilePhotoBtn.BorderColor = System.Drawing.Color.Transparent;
            this.uploadProfilePhotoBtn.BorderWidth = 2;
            this.uploadProfilePhotoBtn.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(219)))), ((int)(((byte)(12)))));
            this.uploadProfilePhotoBtn.ButtonImage = null;
            this.uploadProfilePhotoBtn.CanBeep = true;
            this.uploadProfilePhotoBtn.CanGlow = false;
            this.uploadProfilePhotoBtn.CanShake = true;
            this.uploadProfilePhotoBtn.ContextMenuStripEx = null;
            this.uploadProfilePhotoBtn.CornerRadiusBottomLeft = 10;
            this.uploadProfilePhotoBtn.CornerRadiusBottomRight = 10;
            this.uploadProfilePhotoBtn.CornerRadiusTopLeft = 10;
            this.uploadProfilePhotoBtn.CornerRadiusTopRight = 10;
            this.uploadProfilePhotoBtn.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.uploadProfilePhotoBtn.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.uploadProfilePhotoBtn.EnableLongPress = false;
            this.uploadProfilePhotoBtn.EnablePressAnimation = true;
            this.uploadProfilePhotoBtn.EnableRippleEffect = true;
            this.uploadProfilePhotoBtn.EnableShadow = false;
            this.uploadProfilePhotoBtn.EnableTextWrapping = false;
            this.uploadProfilePhotoBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.uploadProfilePhotoBtn.ForeColor = System.Drawing.Color.Black;
            this.uploadProfilePhotoBtn.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.uploadProfilePhotoBtn.GlowIntensity = 100;
            this.uploadProfilePhotoBtn.GlowRadius = 20F;
            this.uploadProfilePhotoBtn.GradientBackground = false;
            this.uploadProfilePhotoBtn.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(219)))), ((int)(((byte)(12)))));
            this.uploadProfilePhotoBtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.uploadProfilePhotoBtn.HintText = null;
            this.uploadProfilePhotoBtn.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(219)))), ((int)(((byte)(12)))));
            this.uploadProfilePhotoBtn.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.uploadProfilePhotoBtn.HoverTextColor = System.Drawing.Color.Black;
            this.uploadProfilePhotoBtn.HoverTransitionDuration = 250;
            this.uploadProfilePhotoBtn.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.uploadProfilePhotoBtn.ImagePadding = 5;
            this.uploadProfilePhotoBtn.ImageSize = new System.Drawing.Size(16, 16);
            this.uploadProfilePhotoBtn.IsRadial = false;
            this.uploadProfilePhotoBtn.IsReadOnly = false;
            this.uploadProfilePhotoBtn.IsToggleButton = false;
            this.uploadProfilePhotoBtn.IsToggled = false;
            this.uploadProfilePhotoBtn.Location = new System.Drawing.Point(211, 159);
            this.uploadProfilePhotoBtn.LongPressDurationMS = 1000;
            this.uploadProfilePhotoBtn.Name = "uploadProfilePhotoBtn";
            this.uploadProfilePhotoBtn.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.uploadProfilePhotoBtn.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(219)))), ((int)(((byte)(12)))));
            this.uploadProfilePhotoBtn.ParticleCount = 15;
            this.uploadProfilePhotoBtn.PressAnimationScale = 0.97F;
            this.uploadProfilePhotoBtn.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(219)))), ((int)(((byte)(12)))));
            this.uploadProfilePhotoBtn.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.uploadProfilePhotoBtn.PressTransitionDuration = 150;
            this.uploadProfilePhotoBtn.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.uploadProfilePhotoBtn.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.uploadProfilePhotoBtn.RippleOpacity = 0.3F;
            this.uploadProfilePhotoBtn.RippleRadiusMultiplier = 0.6F;
            this.uploadProfilePhotoBtn.ShadowBlur = 5;
            this.uploadProfilePhotoBtn.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.uploadProfilePhotoBtn.ShadowOffset = new System.Drawing.Point(2, 2);
            this.uploadProfilePhotoBtn.ShakeDuration = 500;
            this.uploadProfilePhotoBtn.ShakeIntensity = 5;
            this.uploadProfilePhotoBtn.Size = new System.Drawing.Size(150, 27);
            this.uploadProfilePhotoBtn.TabIndex = 0;
            this.uploadProfilePhotoBtn.Text = "UPLOAD";
            this.uploadProfilePhotoBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.uploadProfilePhotoBtn.TextColor = System.Drawing.Color.Black;
            this.uploadProfilePhotoBtn.TooltipText = null;
            this.uploadProfilePhotoBtn.UseAdvancedRendering = true;
            this.uploadProfilePhotoBtn.UseParticles = false;
            this.uploadProfilePhotoBtn.Visible = false;
            this.uploadProfilePhotoBtn.Click += new System.EventHandler(this.uploadProfilePhoto_Click);
            // 
            // phoneLabel
            // 
            this.phoneLabel.AutoSize = true;
            this.phoneLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phoneLabel.Location = new System.Drawing.Point(367, 379);
            this.phoneLabel.Name = "phoneLabel";
            this.phoneLabel.Size = new System.Drawing.Size(26, 9);
            this.phoneLabel.TabIndex = 17;
            this.phoneLabel.Text = "Phone";
            // 
            // profilePictureBox
            // 
            this.profilePictureBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(35)))), ((int)(((byte)(35)))));
            this.profilePictureBox.IconChar = FontAwesome.Sharp.IconChar.User;
            this.profilePictureBox.IconColor = System.Drawing.Color.White;
            this.profilePictureBox.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.profilePictureBox.IconSize = 150;
            this.profilePictureBox.InitialImage = ((System.Drawing.Image)(resources.GetObject("profilePictureBox.InitialImage")));
            this.profilePictureBox.Location = new System.Drawing.Point(211, 3);
            this.profilePictureBox.Name = "profilePictureBox";
            this.profilePictureBox.Size = new System.Drawing.Size(150, 150);
            this.profilePictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.profilePictureBox.TabIndex = 1;
            this.profilePictureBox.TabStop = false;
            // 
            // profileContainer
            // 
            this.profileContainer.BackColor = System.Drawing.Color.Transparent;
            this.profileContainer.Controls.Add(this.deleteBtn);
            this.profileContainer.Controls.Add(this.label1);
            this.profileContainer.Controls.Add(this.idNumberTbx);
            this.profileContainer.Controls.Add(this.saveBtn);
            this.profileContainer.Controls.Add(this.cancelBtn);
            this.profileContainer.Controls.Add(this.editBtn);
            this.profileContainer.Controls.Add(this.profilePictureBox);
            this.profileContainer.Controls.Add(this.phoneLabel);
            this.profileContainer.Controls.Add(this.uploadProfilePhotoBtn);
            this.profileContainer.Controls.Add(this.emailLabel);
            this.profileContainer.Controls.Add(this.fNameTbx);
            this.profileContainer.Controls.Add(this.bdateLabel);
            this.profileContainer.Controls.Add(this.mNameTbx);
            this.profileContainer.Controls.Add(this.yearLabel);
            this.profileContainer.Controls.Add(this.lNameTbx);
            this.profileContainer.Controls.Add(this.programLabel);
            this.profileContainer.Controls.Add(this.emailTbx);
            this.profileContainer.Controls.Add(this.lnameLabel);
            this.profileContainer.Controls.Add(this.phoneTbx);
            this.profileContainer.Controls.Add(this.mnameLabel);
            this.profileContainer.Controls.Add(this.programTbx);
            this.profileContainer.Controls.Add(this.fnameLabel);
            this.profileContainer.Controls.Add(this.yearTbx);
            this.profileContainer.Controls.Add(this.birthDateTbx);
            this.profileContainer.Location = new System.Drawing.Point(194, 32);
            this.profileContainer.Name = "profileContainer";
            this.profileContainer.Size = new System.Drawing.Size(565, 539);
            this.profileContainer.TabIndex = 18;
            layoutState1.Location = new System.Drawing.Point(3, 493);
            layoutState1.Size = new System.Drawing.Size(194, 188);
            layoutState1.Visible = true;
            this.profileContainer.Tag = layoutState1;
            // 
            // deleteBtn
            // 
            this.deleteBtn.AccessibleDescription = "";
            this.deleteBtn.AccessibleName = "DELETE ACCOUNT";
            this.deleteBtn.AutoSizeBasedOnText = false;
            this.deleteBtn.BackColor = System.Drawing.Color.Transparent;
            this.deleteBtn.BadgeBackColor = System.Drawing.Color.Red;
            this.deleteBtn.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.deleteBtn.BadgeValue = 0;
            this.deleteBtn.BadgeValueForeColor = System.Drawing.Color.White;
            this.deleteBtn.BorderColor = System.Drawing.Color.Transparent;
            this.deleteBtn.BorderWidth = 2;
            this.deleteBtn.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.deleteBtn.ButtonImage = null;
            this.deleteBtn.CanBeep = true;
            this.deleteBtn.CanGlow = false;
            this.deleteBtn.CanShake = true;
            this.deleteBtn.ContextMenuStripEx = null;
            this.deleteBtn.CornerRadiusBottomLeft = 10;
            this.deleteBtn.CornerRadiusBottomRight = 10;
            this.deleteBtn.CornerRadiusTopLeft = 10;
            this.deleteBtn.CornerRadiusTopRight = 10;
            this.deleteBtn.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.deleteBtn.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.deleteBtn.EnableLongPress = false;
            this.deleteBtn.EnablePressAnimation = true;
            this.deleteBtn.EnableRippleEffect = true;
            this.deleteBtn.EnableShadow = false;
            this.deleteBtn.EnableTextWrapping = false;
            this.deleteBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.deleteBtn.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.deleteBtn.GlowIntensity = 100;
            this.deleteBtn.GlowRadius = 20F;
            this.deleteBtn.GradientBackground = false;
            this.deleteBtn.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.deleteBtn.HintText = null;
            this.deleteBtn.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.deleteBtn.HoverTextColor = System.Drawing.Color.White;
            this.deleteBtn.HoverTransitionDuration = 250;
            this.deleteBtn.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteBtn.ImagePadding = 5;
            this.deleteBtn.ImageSize = new System.Drawing.Size(16, 16);
            this.deleteBtn.IsRadial = false;
            this.deleteBtn.IsReadOnly = false;
            this.deleteBtn.IsToggleButton = false;
            this.deleteBtn.IsToggled = false;
            this.deleteBtn.Location = new System.Drawing.Point(211, 495);
            this.deleteBtn.LongPressDurationMS = 1000;
            this.deleteBtn.Name = "deleteBtn";
            this.deleteBtn.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.deleteBtn.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.ParticleCount = 15;
            this.deleteBtn.PressAnimationScale = 0.97F;
            this.deleteBtn.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.deleteBtn.PressTransitionDuration = 150;
            this.deleteBtn.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.deleteBtn.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.deleteBtn.RippleOpacity = 0.3F;
            this.deleteBtn.RippleRadiusMultiplier = 0.6F;
            this.deleteBtn.ShadowBlur = 5;
            this.deleteBtn.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.ShadowOffset = new System.Drawing.Point(2, 2);
            this.deleteBtn.ShakeDuration = 500;
            this.deleteBtn.ShakeIntensity = 5;
            this.deleteBtn.Size = new System.Drawing.Size(150, 27);
            this.deleteBtn.TabIndex = 23;
            this.deleteBtn.TabStop = false;
            this.deleteBtn.Text = "DELETE ACCOUNT";
            this.deleteBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.deleteBtn.TextColor = System.Drawing.Color.White;
            this.deleteBtn.TooltipText = null;
            this.deleteBtn.UseAdvancedRendering = true;
            this.deleteBtn.UseParticles = false;
            this.deleteBtn.Click += new System.EventHandler(this.deleteBtn_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(52, 320);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(43, 9);
            this.label1.TabIndex = 22;
            this.label1.Text = "ID Number";
            // 
            // idNumberTbx
            // 
            this.idNumberTbx.AccessibleDescription = "A customizable text input field.";
            this.idNumberTbx.AccessibleName = "Text Box";
            this.idNumberTbx.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.idNumberTbx.BackColor = System.Drawing.Color.Transparent;
            this.idNumberTbx.BlinkCount = 3;
            this.idNumberTbx.BlinkShadow = false;
            this.idNumberTbx.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.idNumberTbx.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.idNumberTbx.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.idNumberTbx.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.idNumberTbx.CanShake = true;
            this.idNumberTbx.ContinuousBlink = false;
            this.idNumberTbx.CornerRadiusBottomLeft = 10;
            this.idNumberTbx.CornerRadiusBottomRight = 10;
            this.idNumberTbx.CornerRadiusTopLeft = 10;
            this.idNumberTbx.CornerRadiusTopRight = 10;
            this.idNumberTbx.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idNumberTbx.CursorBlinkRate = 500;
            this.idNumberTbx.CursorColor = System.Drawing.Color.Black;
            this.idNumberTbx.CursorHeight = 0;
            this.idNumberTbx.CursorOffset = 0;
            this.idNumberTbx.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.idNumberTbx.CursorWidth = 1;
            this.idNumberTbx.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.idNumberTbx.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.idNumberTbx.DisabledTextColor = System.Drawing.Color.Gray;
            this.idNumberTbx.EnableDropShadow = false;
            this.idNumberTbx.FillColor1 = System.Drawing.Color.White;
            this.idNumberTbx.FillColor2 = System.Drawing.Color.White;
            this.idNumberTbx.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.idNumberTbx.ForeColor = System.Drawing.Color.DimGray;
            this.idNumberTbx.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.idNumberTbx.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.idNumberTbx.IsEnabled = true;
            this.idNumberTbx.IsReadOnly = true;
            this.idNumberTbx.Location = new System.Drawing.Point(55, 336);
            this.idNumberTbx.Name = "idNumberTbx";
            this.idNumberTbx.PlaceholderColor = System.Drawing.Color.Gray;
            this.idNumberTbx.PlaceholderText = "ID Number";
            this.idNumberTbx.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.idNumberTbx.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.idNumberTbx.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.idNumberTbx.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.idNumberTbx.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.idNumberTbx.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.idNumberTbx.ShadowAnimationDuration = 1;
            this.idNumberTbx.ShadowBlur = 10;
            this.idNumberTbx.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.idNumberTbx.Size = new System.Drawing.Size(306, 40);
            this.idNumberTbx.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.idNumberTbx.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.idNumberTbx.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.idNumberTbx.SolidFillColor = System.Drawing.Color.White;
            this.idNumberTbx.TabIndex = 21;
            this.idNumberTbx.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.idNumberTbx.ValidationErrorMessage = "Invalid input.";
            this.idNumberTbx.ValidationFunction = null;
            // 
            // saveBtn
            // 
            this.saveBtn.AccessibleDescription = "";
            this.saveBtn.AccessibleName = "SAVE";
            this.saveBtn.AutoSizeBasedOnText = false;
            this.saveBtn.BackColor = System.Drawing.Color.Transparent;
            this.saveBtn.BadgeBackColor = System.Drawing.Color.Red;
            this.saveBtn.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.saveBtn.BadgeValue = 0;
            this.saveBtn.BadgeValueForeColor = System.Drawing.Color.White;
            this.saveBtn.BorderColor = System.Drawing.Color.Transparent;
            this.saveBtn.BorderWidth = 2;
            this.saveBtn.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.saveBtn.ButtonImage = null;
            this.saveBtn.CanBeep = true;
            this.saveBtn.CanGlow = false;
            this.saveBtn.CanShake = true;
            this.saveBtn.ContextMenuStripEx = null;
            this.saveBtn.CornerRadiusBottomLeft = 10;
            this.saveBtn.CornerRadiusBottomRight = 10;
            this.saveBtn.CornerRadiusTopLeft = 10;
            this.saveBtn.CornerRadiusTopRight = 10;
            this.saveBtn.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.saveBtn.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.saveBtn.EnableLongPress = false;
            this.saveBtn.EnablePressAnimation = true;
            this.saveBtn.EnableRippleEffect = true;
            this.saveBtn.EnableShadow = false;
            this.saveBtn.EnableTextWrapping = false;
            this.saveBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.saveBtn.ForeColor = System.Drawing.Color.White;
            this.saveBtn.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.saveBtn.GlowIntensity = 100;
            this.saveBtn.GlowRadius = 20F;
            this.saveBtn.GradientBackground = false;
            this.saveBtn.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.saveBtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.saveBtn.HintText = null;
            this.saveBtn.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.saveBtn.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.saveBtn.HoverTextColor = System.Drawing.Color.White;
            this.saveBtn.HoverTransitionDuration = 250;
            this.saveBtn.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.saveBtn.ImagePadding = 5;
            this.saveBtn.ImageSize = new System.Drawing.Size(16, 16);
            this.saveBtn.IsRadial = false;
            this.saveBtn.IsReadOnly = false;
            this.saveBtn.IsToggleButton = false;
            this.saveBtn.IsToggled = false;
            this.saveBtn.Location = new System.Drawing.Point(55, 462);
            this.saveBtn.LongPressDurationMS = 1000;
            this.saveBtn.Name = "saveBtn";
            this.saveBtn.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.saveBtn.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.saveBtn.ParticleCount = 15;
            this.saveBtn.PressAnimationScale = 0.97F;
            this.saveBtn.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.saveBtn.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.saveBtn.PressTransitionDuration = 150;
            this.saveBtn.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.saveBtn.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.saveBtn.RippleOpacity = 0.3F;
            this.saveBtn.RippleRadiusMultiplier = 0.6F;
            this.saveBtn.ShadowBlur = 5;
            this.saveBtn.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.saveBtn.ShadowOffset = new System.Drawing.Point(2, 2);
            this.saveBtn.ShakeDuration = 500;
            this.saveBtn.ShakeIntensity = 5;
            this.saveBtn.Size = new System.Drawing.Size(150, 27);
            this.saveBtn.TabIndex = 20;
            this.saveBtn.Text = "SAVE";
            this.saveBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.saveBtn.TextColor = System.Drawing.Color.White;
            this.saveBtn.TooltipText = null;
            this.saveBtn.UseAdvancedRendering = true;
            this.saveBtn.UseParticles = false;
            this.saveBtn.Visible = false;
            this.saveBtn.Click += new System.EventHandler(this.saveBtn_Click);
            // 
            // cancelBtn
            // 
            this.cancelBtn.AccessibleDescription = "";
            this.cancelBtn.AccessibleName = "CANCEL";
            this.cancelBtn.AutoSizeBasedOnText = false;
            this.cancelBtn.BackColor = System.Drawing.Color.Transparent;
            this.cancelBtn.BadgeBackColor = System.Drawing.Color.Red;
            this.cancelBtn.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.cancelBtn.BadgeValue = 0;
            this.cancelBtn.BadgeValueForeColor = System.Drawing.Color.White;
            this.cancelBtn.BorderColor = System.Drawing.Color.Transparent;
            this.cancelBtn.BorderWidth = 2;
            this.cancelBtn.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.cancelBtn.ButtonImage = null;
            this.cancelBtn.CanBeep = true;
            this.cancelBtn.CanGlow = false;
            this.cancelBtn.CanShake = true;
            this.cancelBtn.ContextMenuStripEx = null;
            this.cancelBtn.CornerRadiusBottomLeft = 10;
            this.cancelBtn.CornerRadiusBottomRight = 10;
            this.cancelBtn.CornerRadiusTopLeft = 10;
            this.cancelBtn.CornerRadiusTopRight = 10;
            this.cancelBtn.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.cancelBtn.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.cancelBtn.EnableLongPress = false;
            this.cancelBtn.EnablePressAnimation = true;
            this.cancelBtn.EnableRippleEffect = true;
            this.cancelBtn.EnableShadow = false;
            this.cancelBtn.EnableTextWrapping = false;
            this.cancelBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cancelBtn.ForeColor = System.Drawing.Color.White;
            this.cancelBtn.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.cancelBtn.GlowIntensity = 100;
            this.cancelBtn.GlowRadius = 20F;
            this.cancelBtn.GradientBackground = false;
            this.cancelBtn.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.cancelBtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.cancelBtn.HintText = null;
            this.cancelBtn.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.cancelBtn.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.cancelBtn.HoverTextColor = System.Drawing.Color.White;
            this.cancelBtn.HoverTransitionDuration = 250;
            this.cancelBtn.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cancelBtn.ImagePadding = 5;
            this.cancelBtn.ImageSize = new System.Drawing.Size(16, 16);
            this.cancelBtn.IsRadial = false;
            this.cancelBtn.IsReadOnly = false;
            this.cancelBtn.IsToggleButton = false;
            this.cancelBtn.IsToggled = false;
            this.cancelBtn.Location = new System.Drawing.Point(367, 462);
            this.cancelBtn.LongPressDurationMS = 1000;
            this.cancelBtn.Name = "cancelBtn";
            this.cancelBtn.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.cancelBtn.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.cancelBtn.ParticleCount = 15;
            this.cancelBtn.PressAnimationScale = 0.97F;
            this.cancelBtn.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.cancelBtn.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.cancelBtn.PressTransitionDuration = 150;
            this.cancelBtn.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.cancelBtn.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.cancelBtn.RippleOpacity = 0.3F;
            this.cancelBtn.RippleRadiusMultiplier = 0.6F;
            this.cancelBtn.ShadowBlur = 5;
            this.cancelBtn.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.cancelBtn.ShadowOffset = new System.Drawing.Point(2, 2);
            this.cancelBtn.ShakeDuration = 500;
            this.cancelBtn.ShakeIntensity = 5;
            this.cancelBtn.Size = new System.Drawing.Size(150, 27);
            this.cancelBtn.TabIndex = 19;
            this.cancelBtn.Text = "CANCEL";
            this.cancelBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cancelBtn.TextColor = System.Drawing.Color.White;
            this.cancelBtn.TooltipText = null;
            this.cancelBtn.UseAdvancedRendering = true;
            this.cancelBtn.UseParticles = false;
            this.cancelBtn.Visible = false;
            this.cancelBtn.Click += new System.EventHandler(this.cancelBtn_Click);
            // 
            // editBtn
            // 
            this.editBtn.AccessibleDescription = "";
            this.editBtn.AccessibleName = "EDIT";
            this.editBtn.AutoSizeBasedOnText = false;
            this.editBtn.BackColor = System.Drawing.Color.Transparent;
            this.editBtn.BadgeBackColor = System.Drawing.Color.Red;
            this.editBtn.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.editBtn.BadgeValue = 0;
            this.editBtn.BadgeValueForeColor = System.Drawing.Color.White;
            this.editBtn.BorderColor = System.Drawing.Color.Transparent;
            this.editBtn.BorderWidth = 2;
            this.editBtn.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(219)))), ((int)(((byte)(12)))));
            this.editBtn.ButtonImage = null;
            this.editBtn.CanBeep = true;
            this.editBtn.CanGlow = false;
            this.editBtn.CanShake = true;
            this.editBtn.ContextMenuStripEx = null;
            this.editBtn.CornerRadiusBottomLeft = 10;
            this.editBtn.CornerRadiusBottomRight = 10;
            this.editBtn.CornerRadiusTopLeft = 10;
            this.editBtn.CornerRadiusTopRight = 10;
            this.editBtn.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.editBtn.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.editBtn.EnableLongPress = false;
            this.editBtn.EnablePressAnimation = true;
            this.editBtn.EnableRippleEffect = true;
            this.editBtn.EnableShadow = false;
            this.editBtn.EnableTextWrapping = false;
            this.editBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.editBtn.ForeColor = System.Drawing.Color.White;
            this.editBtn.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.editBtn.GlowIntensity = 100;
            this.editBtn.GlowRadius = 20F;
            this.editBtn.GradientBackground = false;
            this.editBtn.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.editBtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.editBtn.HintText = null;
            this.editBtn.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.editBtn.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.editBtn.HoverTextColor = System.Drawing.Color.White;
            this.editBtn.HoverTransitionDuration = 250;
            this.editBtn.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.editBtn.ImagePadding = 5;
            this.editBtn.ImageSize = new System.Drawing.Size(16, 16);
            this.editBtn.IsRadial = false;
            this.editBtn.IsReadOnly = false;
            this.editBtn.IsToggleButton = false;
            this.editBtn.IsToggled = false;
            this.editBtn.Location = new System.Drawing.Point(211, 462);
            this.editBtn.LongPressDurationMS = 1000;
            this.editBtn.Name = "editBtn";
            this.editBtn.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.editBtn.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.editBtn.ParticleCount = 15;
            this.editBtn.PressAnimationScale = 0.97F;
            this.editBtn.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.editBtn.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.editBtn.PressTransitionDuration = 150;
            this.editBtn.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.editBtn.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.editBtn.RippleOpacity = 0.3F;
            this.editBtn.RippleRadiusMultiplier = 0.6F;
            this.editBtn.ShadowBlur = 5;
            this.editBtn.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.editBtn.ShadowOffset = new System.Drawing.Point(2, 2);
            this.editBtn.ShakeDuration = 500;
            this.editBtn.ShakeIntensity = 5;
            this.editBtn.Size = new System.Drawing.Size(150, 27);
            this.editBtn.TabIndex = 18;
            this.editBtn.Text = "EDIT";
            this.editBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.editBtn.TextColor = System.Drawing.Color.Black;
            this.editBtn.TooltipText = null;
            this.editBtn.UseAdvancedRendering = true;
            this.editBtn.UseParticles = false;
            this.editBtn.Click += new System.EventHandler(this.editBtn_Click);
            // 
            // mySiticoneLicenseSettings1
            // 
            this.mySiticoneLicenseSettings1.OpenLicenseSettings = null;
            // 
            // ViewProfileForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1010, 605);
            this.Controls.Add(this.profileContainer);
            this.Name = "ViewProfileForm";
            this.StateCommon.Border.Color1 = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(35)))), ((int)(((byte)(35)))));
            this.StateCommon.Border.Color2 = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(35)))), ((int)(((byte)(35)))));
            this.Load += new System.EventHandler(this.ProfileForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.profilePictureBox)).EndInit();
            this.profileContainer.ResumeLayout(false);
            this.profileContainer.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.OpenFileDialog openFileDialog1;
        private SiticoneNetFrameworkUI.SiticoneTextBox birthDateTbx;
        private SiticoneNetFrameworkUI.SiticoneTextBox yearTbx;
        private System.Windows.Forms.Label fnameLabel;
        private SiticoneNetFrameworkUI.SiticoneTextBox programTbx;
        private System.Windows.Forms.Label mnameLabel;
        private SiticoneNetFrameworkUI.SiticoneTextBox phoneTbx;
        private System.Windows.Forms.Label lnameLabel;
        private SiticoneNetFrameworkUI.SiticoneTextBox emailTbx;
        private System.Windows.Forms.Label programLabel;
        private SiticoneNetFrameworkUI.SiticoneTextBox lNameTbx;
        private System.Windows.Forms.Label yearLabel;
        private SiticoneNetFrameworkUI.SiticoneTextBox mNameTbx;
        private System.Windows.Forms.Label bdateLabel;
        private SiticoneNetFrameworkUI.SiticoneTextBox fNameTbx;
        private System.Windows.Forms.Label emailLabel;
        private SiticoneNetFrameworkUI.SiticoneButton uploadProfilePhotoBtn;
        private System.Windows.Forms.Label phoneLabel;
        private FontAwesome.Sharp.IconPictureBox profilePictureBox;
        private System.Windows.Forms.Panel profileContainer;
        private SiticoneNetFrameworkUI.SiticoneButton editBtn;
        private SiticoneNetFrameworkUI.SiticoneButton cancelBtn;
        private SiticoneNetFrameworkUI.SiticoneButton saveBtn;
        private System.Windows.Forms.Label label1;
        private SiticoneNetFrameworkUI.SiticoneTextBox idNumberTbx;
        private SiticoneNetFrameworkUI.MySiticoneLicenseSettings mySiticoneLicenseSettings1;
        private SiticoneNetFrameworkUI.SiticoneButton deleteBtn;
    }
}